const types = {
  // User actions
  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  USER_LOGOUT: "USER_LOGOUT",

  // User actions
  USER_CHECK_SESSION: "USER_CHECK_SESSION",
  USER_CHECK_SESSION_SUCCESS: "USER_CHECK_SESSION_SUCCESS",
  USER_CHECK_SESSION_FAILURE: "USER_CHECK_SESSION_FAILURE",

  // Fetch post
  FETCH_POST: "FETCH_POST",
  FETCH_POST_SUCCESS: "FETCH_POST_SUCCESS",
  FETCH_POST_FAILURE: "FETCH_POST_FAILURE",

  // Fetch categories
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILURE: "FETCH_CATEGORIES_FAILURE",

  // Fetch posts
  FETCH_POSTS: "FETCH_POSTS",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAILURE: "FETCH_POSTS_FAILURE",

  // Create post
  CREATE_POST: "CREATE_POST",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",

  // Delete post
  DELETE_POST: "DELETE_POST",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",

  // Edit post
  UPDATE_POST: "UPDATE_POST",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILURE: "UPDATE_POST_FAILURE",

  // Like post
  LIKE_POST: "LIKE_POST",
  LIKE_POST_SUCCESS: "LIKE_POST_SUCCESS",
  LIKE_POST_FAILURE: "LIKE_POST_FAILURE",

  // Like post
  UNLIKE_POST: "UNLIKE_POST",
  UNLIKE_POST_SUCCESS: "UNLIKE_POST_SUCCESS",
  UNLIKE_POST_FAILURE: "UNLIKE_POST_FAILURE",

  // Create comment
  CREATE_COMMENT: "CREATE_COMMENT",
  CREATE_COMMENT_SUCCESS: "CREATE_COMMENT_SUCCESS",
  CREATE_COMMENT_FAILURE: "CREATE_COMMENT_SUCCESS",

  // Delete Comment
  DELETE_COMMENT: "DELETE_COMMENT",
  DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
  DELETE_COMMENT_FAILURE: "DELETE_COMMENT_FAILURE",
};

export default types;