const types = {
  FETCH_POST: "FETCH_POST",
  FETCH_POST_SUCCESS: "FETCH_POST_SUCCESS",
  FETCH_POST_FAILURE: "FETCH_POST_FAILURE",
  FETCH_POSTS: "FETCH_POSTS",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAILURE: "FETCH_POSTS_FAILURE",
  CREATE_POST: "CREATE_POST",
  DELETE_POST: "DELETE_POST",
  EDIT_POST: "DELETE_POST",
  RATE_POST: "RATE_POST",
  CREATE_COMMENT: "CREATE_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
};

export default types;